#!/bin/bash

# only machines that have spotify and music-control
# (https://github.com/VectorCell/music-control)
if [ -n "$(which sp-current)" ] && [ -n "$(which spotify)" ]; then
	if [ -n "$(top -b -n 1 | grep spotify)" ]; then
		echo -n "#[fg=colour159] $(sp-current) "
	fi
fi

# for eniac, which controls the relays
if [ "$HOSTNAME" == "eniac" ]; then
	mcp9808_c | ctof -r | tr -d '\n'
	echo -n "°F "
fi

if [ -n "$(top -b -n 1 | grep vnc)" ]; then
	echo -n "#[fg=white] VNC "
fi

if [ "$HOSTNAME" == "torrent-dl" ]; then
	IPADDRLOTUS=$(sudo su bismith -c 'ssh lotus.local "~/bin/tmux-publicip" | tr -d "\n "')
	IPADDRTORRENTDL=$(tmux-publicip | tr -d '\n')
	if [ "$IPADDRLOTUS" == "$IPADDRTORRENTDL" ]; then
		echo -n " ERROR: VPN OFF "
	else
		echo -n " VPN ON "
	fi
fi

#if [ $HOSTNAME == Green ] || [ $HOSTNAME == Precisix ] || [ $HOSTNAME == Yogix ]; then
#	echo -n "#[fg=colour159]$(tmux-weather)"
#fi
