#!/bin/bash

echo -n " "

# if there is a way to get the cpu temp in this machine, it should be returned
# by a script named temp in the user's path
if [ -n "$(which temp)" ]; then
	temp | tr -d '\n'
	echo -n " "
fi

loadavg=$(uptime | rev | awk '{print $1,$2,$3}' | rev | tr -d '\n,')
echo -n "$loadavg "
