#!/bin/bash

echo -n " "

exclude="lo|docker0"
if [ "$HOSTNAME" == "Precision390" ]; then
	# for some reason this machine is convinced it has a wireless adapter
	exclude="${exclude}|wlan0"
fi

for interface in $(ls /sys/class/net | grep -v -E "$exclude"); do
	address=$(ip addr show | grep $interface | grep inet | tr '/' ' ' | awk '{print $2}')

	if [ -z "$address" ]; then
		address="?"
	elif [ "$(echo $interface | colrm 2)" == "e" ] || [ "$(echo $interface | colrm 2)" == "w" ]; then
		if [ "$(echo $address | tr '.' ' ' | awk '{print $1,$2}')" == "192 168" ]; then
			address=$(echo $address | tr '.' ' ' | awk '{print $4}')
		fi
	elif [ "$(echo $interface | colrm 8)" == "vboxnet" ]; then
		address=$(echo $address | tr '.' ' ' | awk '{print $4}')
	elif [ $interface == "nrtap" ]; then
		address=$(echo $address | tr '.' ' ' | awk '{print $4}')
	fi

	echo -n $(echo $interface | colrm 2)
	echo -n "$address "
done
