#!/bin/bash

# only machines that have spotify and music-control
# (https://github.com/VectorCell/music-control)
if [ -n "$(which sp-current)" ] && [ -n "$(which spotify)" ]; then
	if [ -n "$(top -b -n 1 | grep spotify)" ]; then
		echo -n "#[fg=colour159] $(sp-current) "
	fi
fi

# for PiOne, who controls the relays
if [ "$HOSTNAME" == "PiOne" ]; then
	relays status | grep " on " | awk '{print $1}' | tr '\n' ' '
fi

#echo -n "#[fg=colour159] $(tmux-weather) "
