#!/bin/bash

# this script needs a serious overhaul to be more generic to all systems
# as of right now it works fine on Yogix

if [ "$HOSTNAME" == "Yogix" ]; then
	echo -n " "
	df -h | grep sdb1 | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep sdb2 | awk '{print $4,""}' | tr -d 'G\n'
	count=0
	df -h | grep "/media/$(whoami)" | while read line; do
		echo "$line" | tr '/' ' ' | rev | awk '{print $1}' | rev | tr -d '\n'
		echo -n "-"
		echo "$line" | awk '{print $4}' | tr -d 'G\n'
		echo -n " "
	done
elif [ "$HOSTNAME" == "lotus" ]; then
	echo -n " "
	df -h | grep /$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep ssd$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep ALPHA$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep BETA$ | awk '{print $4,""}' | tr -d 'G\n'
elif [ "$(lscpu | grep Arch | awk '{print $2}' | colrm 5)" == "armv" ]; then
	echo -n " "
	df -h | grep "/$" | head -n 1 | awk '{print $4}' | tr -d 'G\n'
	echo -n " "
	for letter in {a..z}; do
		disk=$(ls /dev/sd$letter 2> /dev/null)
		if [ -n "$disk" ]; then
			df -h | grep $disk | while read line; do
				>&2 echo "checking $disk"
				label=$(echo $line | tr '/' '\n' | tail -n 1)
				free=$(echo $line | awk '{print $4}' | tr -d 'G')
				if [ -n "$label" ]; then
					echo "$label" | colrm 3 | tr -d '\n'
					echo -n "-${free} "
				else
					echo -n "$free "
				fi
			done
		fi
	done
else

	# for other systems, just show information for root partition

	echo -n " "
	free=$(df -h | grep /$ | awk '{print $4}')
	echo -n "$free "
fi

