#!/bin/bash

# this script needs a serious overhaul to be more generic to all systems
# as of right now it works fine on Yogix

if [ "$HOSTNAME" == "Yogix" ]; then
	echo -n " "
	df -h | grep sdb1 | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep sdb2 | awk '{print $4,""}' | tr -d 'G\n'
	count=0
	df -h | grep "/media/$(whoami)" | while read line; do
		echo "$line" | tr '/' ' ' | rev | awk '{print $1}' | rev | tr -d '\n'
		echo -n "-"
		echo "$line" | awk '{print $4}' | tr -d 'G\n'
		echo -n " "
	done
elif [ "$HOSTNAME" == "lotus" ]; then
	echo -n " "
	df -h | grep /$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep internal$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep BETA$ | awk '{print $4,""}' | tr -d 'G\n'

elif [ "$HOSTNAME" == "tank" ]; then
	echo -n " "
	df -h | grep /$ | awk '{print $4,""}' | tr -d 'G\n'

elif [ "$HOSTNAME" == "nissan" ]; then
	echo -n " "
	df -h | grep /$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep -E "ALPHA$|BETA$" | awk '{print $4,""}' | tr -d 'G\n'

elif [ "$HOSTNAME" == "toyota" ]; then
	echo -n " "
	df -h | grep /$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep -E "sandisk$" | awk '{print "sandisk",$4,""}' | tr -d 'G\n'

elif [ "$HOSTNAME" == "precisix" ]; then
	echo -n " "
	df -h | grep /$ | awk '{print $4,""}' | tr -d 'G\n'
	df -h | grep internal$ | awk '{print $4,""}' | tr -d 'G\n'

elif [ "$HOSTNAME" == "Green" ]; then
	echo -n " "

#	lsblk | awk '{print $7}' | while read mountpoint; do
#		if [ -n "$mountpoint" ]; then
#			#echo "$mountpoint "
#			df -hT $mountpoint 2> /dev/null | tail -n 1 | awk '{print $5,""}' | tr -d 'G\n'
#		fi
#	done

	df -h / | grep /$ | awk '{print $4,""}' | tr -d "G\n"
	#df -hT | grep zfs | awk '{print $1,$5,""}' | tr -d 'G\n'

#	ls /dev/disk/by-id | grep -v part | grep ata-WDC_WD40EFRX | while read diskid; do
#		sudo hddtemp /dev/disk/by-id/$diskid | rev | awk '{print $1}' | rev | tr -d '\n'
#		echo -n " "
#	done

#	sudo hddtemp $(sudo blkid | grep ALPHA | colrm 9) | rev | colrm 1 2 | awk '{print $1}' | rev | tr '\n' ' '
#	sudo blkid | grep store | colrm 9 | while read line; do
#		sudo hddtemp $line | rev | colrm 1 2 | awk '{print $1}' | rev | tr '\n' ' '
#	done

elif [ "$HOSTNAME" == "leander" ]; then
	echo -n " "
	df -h / | tail -n 1 | awk '{print $4}' | tr -d 'G\n'
	echo -n ' '
	#df -hT | grep zfs | awk '{print $1,$5,""}' | tr -d 'G\n'

elif [ "$(lscpu | grep Arch | awk '{print $2}' | colrm 5)" == "armv" ]; then
	echo -n " "
	df -h | grep "/$" | head -n 1 | awk '{print $4}' | tr -d 'G\n'
	echo -n " "
	for letter in {a..z}; do
		disk=$(ls /dev/sd$letter 2> /dev/null)
		if [ -n "$disk" ]; then
			df -h | grep $disk | while read line; do
				>&2 echo "checking $disk"
				label=$(echo $line | tr '/' '\n' | tail -n 1)
				free=$(echo $line | awk '{print $4}' | tr -d 'G')
				if [ -n "$label" ]; then
					echo "$label" | colrm 3 | tr -d '\n'
					echo -n "-${free} "
				else
					echo -n "$free "
				fi
			done
		fi
	done
else

	# for other systems, just show information for root partition
	# and zfs pools

	echo -n " "
	free=$(df -h | grep /$ | awk '{print $4}' | tr -d 'G')
	echo -n "$free "

	#df -hT | grep zfs | awk '{print $1,$5}' | tr '\n' ' ' | tr -d 'G\n'
fi

df -hT | grep zfs | awk '{print $1,$5}' | tr '\n' ' ' | tr -d 'G\n'
echo
